language: erlang
services:
  - redis
before_install:
  - mkdir -p vendor/elixir
  - wget -q https://github.com/elixir-lang/elixir/releases/download/v0.12.4/v0.12.4.zip && unzip -qq v0.12.4.zip -d vendor/elixir
  - export PATH="$PATH:$PWD/vendor/elixir/bin"
  - export MIX_ENV=test
install: mix deps.get
otp_release:
  - R16B03-1
  - R16B03
  - R16B02
  - R16B01
  - R16B
script: mix test
notifications:
  email: false